Making lr-run-app take list of applications to run

diff --git a/script/checkout b/script/checkout
--- a/script/checkout
+++ b/script/checkout
@@ -35,9 +35,7 @@ function is_valid_app {
 }
 
 function get_directory_for_app {
-  local app=$1
-
-  
+  local app=$1  
 }
 
 function update_development_environment {
@@ -80,14 +78,14 @@ function update_app {
 }
 
 function install_requirements {
-  local app_name=$1
+  local app_dir="/vagrant/apps/${1}"
 
-  if [[ -f ./requirements.txt ]] ; then
-    pip install -r ./requirements.txt
+  if [[ -f ${app_dir}/requirements.txt ]] ; then
+    pip install -r ${app_dir}/requirements.txt
   fi 
 
-  if [[ -f ./requirements_test.txt ]] ; then
-    pip install -r ./requirements_test.txt
+  if [[ -f ${app_dir}/requirements_test.txt ]] ; then
+    pip install -r ${app_dir}/requirements_test.txt
   fi 
 }
 
@@ -118,4 +116,25 @@ function remove_virtual_env {
     rmvirtualenv ${app_name}
     set -e
   fi
+}
+
+function check_all_apps_are_valid {
+  local apps_to_start=(${@})
+
+  for app_to_start in ${apps_to_start}; do
+    if [[ $(is_valid_app ${apps_to_start}) != 1 ]] ; then
+      echo "Can't find an app called ${apps_to_start} in the configuration file in /vagrant/config/apps"
+      exit 1
+    fi
+  done
+}
+
+function configure_virtual_env_for_apps {
+  local apps_to_start=(${@})
+
+  for app_to_start in ${apps_to_start}; do
+    echo "Configuring virtual environment for ${apps_to_start}"
+    create_virtual_env ${apps_to_start}
+    install_requirements ${app_to_start}  
+  done
 }
diff --git a/script/dev/bin/lr-run-app b/script/dev/bin/lr-run-app
--- a/script/dev/bin/lr-run-app
+++ b/script/dev/bin/lr-run-app
@@ -12,8 +12,7 @@ case `uname` in
 		fi
 	;;
 
-	*)
-		
+	*)	
 		echo
 		echo
 		echo "You need to be running in your vagrant virtual machine to run this."
@@ -24,28 +23,31 @@ case `uname` in
 	;;
 esac
 
-if [[ ! -f run.sh ]] ; then		
-		echo
-		echo "You haven't supplied an application name and there is no run.sh in the current directory [`pwd`]"
-		echo "I don't know what applications you want me to start!"
-		echo
-		echo "Either run this script from an application directory in /vagrant/apps"
-		echo "or pass in application names by executing" 
-		echo
-		echo "lr-run-app app1 app2 app3"
-		echo
-		exit 0 # Not necessarily an error, some apps are not auto-startable
-fi
-
 source /vagrant/script/checkout
 
-if [[ $(is_valid_app $1) != 1 ]] ; then
-	echo "Can't find an app called $1 in the configuration file in /vagrant/config/apps"
-	exit 1
+args=(${@})
+first_arg=${args[0]}
+apps_to_start=()
+
+if [ -z ${first_arg} ]; then
+	# We've not been called with any arguments. Let's see if we're in an
+	# application directory with a run.sh
+
+	if [ -f ./run.sh ]; then
+	  apps_to_start=$(basename `pwd`)
+	else
+	  echo 
+	  echo "You've called this script without specifiy which apps you need and I can't find a run.sh" 
+	  echo "in the current directory [`pwd`]" 
+	  echo 
+	  echo "You either need to specify some apps, or lr-run-app from the base directory of an app with a run.sh" 
+	  echo 
+	  exit 1
+	fi
 fi
 
-create_virtual_env $1
-install_requirements
+check_all_apps_are_valid ${app_to_start}
+configure_virtual_env_for_apps ${apps_to_start}
 
 # TODO: MW - tech debt --
 # Currently our run.sh scripts in the apps don't always work with set -e in place
